version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: industrial-brain-postgres
    restart: always
    environment:
      POSTGRES_DB: indusMind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abhi2004 
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5.12.0-community
    container_name: industrial-brain-neo4j
    restart: always
    ports:
      - "7474:7474" # Neo4j Browser UI
      - "7687:7687" # Bolt protocol port
    environment:
      - NEO4J_AUTH=neo4j/abhi2004
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
